### ISSUE TITLE
Add external arakoon validation test suite

### ISSUE THREAD

**Issue by pploegaert** [openvstorage/integrationtests#444] opened 2017-02-27 12:46 UTC
Covering:
https://github.com/openvstorage/framework-alba-plugin/issues/284
https://github.com/openvstorage/framework-alba-plugin/issues/321

**Comment by JeffreyDevloo** [comment] 2017-04-03 13:12
Duplicate of https://github.com/openvstorage/integrationtests/issues/433

**Closed by JeffreyDevloo** 2017-04-03 13:12 UTC
Labels: priority_normal
