### ISSUE TITLE
VM creation fails on EE-VIR-4N-199.191-fwk-develop in ci_scenario_edge_test

### ISSUE THREAD

**Issue by jake9050** [openvstorage/integrationtests#579] opened 2017-07-26 08:58 UTC
Environment EE-VIR-4N-199.191-fwk-develop

```
2017-07-26 00:50:05 99600 +0200 - ovs-node01-1604 - 11552/140699579442944 - scenario_helpers/vm_handler - 3346 - INFO - Boot VDisk successfully created.
2017-07-26 00:50:17 65200 +0200 - ovs-node01-1604 - 11552/140699579442944 - scenario_helpers/vm_handler - 3360 - INFO - VDisk data_vdisk successfully created!
2017-07-26 00:50:18 11300 +0200 - ovs-node01-1604 - 11552/140699579442944 - scenario_helpers/vm_handler - 3362 - WARNING - Could not fetch the cd vdisk after 0.0208010673523s.
2017-07-26 00:50:18 61600 +0200 - ovs-node01-1604 - 11552/140699579442944 - scenario_helpers/vm_handler - 3363 - WARNING - Could not fetch the cd vdisk after 0.523992061615s.
2017-07-26 00:50:19 11900 +0200 - ovs-node01-1604 - 11552/140699579442944 - scenario_helpers/vm_handler - 3364 - WARNING - Could not fetch the cd vdisk after 1.02754616737s.
2017-07-26 00:50:20 25700 +0200 - ovs-node01-1604 - 11552/140699579442944 - scenario_helpers/vm_handler - 3367 - INFO - Prepped everything for VM mds-regression-000.
2017-07-26 00:50:20 26800 +0200 - ovs-node01-1604 - 11552/140699579442944 - scenario_helpers/vm_handler - 3369 - INFO - Creating VM `mds-regression-000`
2017-07-26 00:50:21 94000 +0200 - ovs-node01-1604 - 11552/140698181281536 - scenario_helpers/vm_handler - 3372 - ERROR - Error while listening for VM messages.. Got [Errno 98] Address already in use: None

========= Remote Traceback (1) =========
Traceback (most recent call last):
  File "/tmp/tmp.CSo0D3Vz7U/rpyc/core/protocol.py", line 305, in _dispatch_request
    res = self._HANDLERS[handler](self, *args)
  File "/tmp/tmp.CSo0D3Vz7U/rpyc/core/protocol.py", line 535, in _handle_call
    return self._local_objects[oid](*args, **dict(kwargs))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address already in use

2017-07-26 00:50:23 90300 +0200 - ovs-node01-1604 - 11552/140699579442944 - scenario_helpers/vm_handler - 3377 - INFO - Created VM `mds-regression-000`!

```

**Comment by JeffreyDevloo** [comment] 2017-08-14 07:44
Duplicate of: https://github.com/openvstorage/integrationtests/issues/586

**Closed by JeffreyDevloo** 2017-08-14 07:44 UTC
Labels: process_duplicate
